### ISSUE TITLE
Update the version of Alpine in governmentpaas/curl-ssl

### ISSUE THREAD

**Issue by vadimeisenbergibm** [alphagov/paas-docker-cloudfoundry-tools#153]
The current Alpine version, 3.3, has DNS problems with Kubernetes. Is it possible to update it to 3.8?

A related issue gliderlabs/docker-alpine#255.

**Comment by richardTowers** [comment]
Hi @vadimeisenbergibm - thanks for this issue. We'll have a look at updating to 3.8.

I'd caution against using this image for anything production-like though - it's maintained for internal use cases, and we don't provide any guarantees of stability, security or fitness for purpose.

**Comment by vadimeisenbergibm** [comment]
Hi @richardTowers, thank you! I do not intend to use this image for production, only for testing and demos of [istio.io](https://istio.io)
