### ISSUE TITLE
governmentpaas/git-ssh:latest is now missing "curl"

### ISSUE THREAD

**Issue by fboes** [alphagov/paas-docker-cloudfoundry-tools#155]
Deployment based on this image set to ":latest" do now fail, because "Curl" is missing:

* Last working deployment with this image succeeded at Apr 24, 2019 2:12pm GMT+0200
* First broken deployment with this image failing because of missing CURL failed at Apr 25, 2019 9:48am GMT+0200
* Deployments succeeded after setting deployment image to `governmentpaas/git-ssh:f120938e7390ec36314ec037465a1b35a079243e`

The `README.md` says:

> Git also includes by default curl, OpenSSL and ca-certificates.

This seems no longer to be true. ;)

**Proposal**: Either add `curl` to `ENV PACKAGES`, or remove "curl" from `README.md`.

**Comment by tlwr** [comment]
👏 Thanks for raising this @fboes
