### ISSUE TITLE
No multiarch compatible images

### ISSUE THREAD

**Issue by knm3000** [alphagov/paas-docker-cloudfoundry-tools#192]
Is it possible to build / publish to docker hub `curl-ssl` image for multiple platforms (e.g s390x)? Thanks.

**Comment by AP-Hunt** [comment]
Hi Konstantin,

We wouldn't build & publish these images for other platforms, no, sorry. They're all MIT licensed, though. If the `curl-ssl` container otherwise meet your needs, you're welcome to build it for your target platform yourself using our Dockerfile.

Regards,
Andy
