### ISSUE TITLE
Support v6 releases

### ISSUE THREAD

**Issue by oysteing** [alphagov/paas-docker-cloudfoundry-tools#194]
It would be nice if a branch could support Docker Hub tags for v6 releases for a while, as v7 doesn't seem to be fully backward compatible.

**Comment by tlwr** [comment]
Hi @oysteing 

We tag the docker images with the git digest, so you can reference a particular commit in time.

Alternatively do you mean, you would like docker images with v6 patch releases, eg a `governmentpaas/cf-cli-v6` image

**Comment by oysteing** [comment]
Exatctly. I'm currently referencing a specific tag hash, but to have the latest v6 release, governmentpaas/cf-cli:cf-cli-v6 would be much more convenient.

Thanks for sharing the image, btw!

**Comment by tlwr** [comment]
I'll have to think about this a bit more...

Right now the process isn't particularly automated for updating dependencies

If we track upstream versions and automatically generate an image that looks like `governmentpaas/cf-cli:cf-cli_v6.50.1_ruby_2.7.1` then we wouldn't have to keep bumping versions and there would be more versions available

**Comment by 46bit** [comment]
Hi. This isn't something we've needed to do, and I'm afraid we don't have the time to make images with features for others. All the best.
