### ISSUE TITLE
Upgrade terraform to 0.13.5

### ISSUE THREAD

**Issue by acwn1976** [alphagov/paas-docker-cloudfoundry-tools#201]
We use your container to build our environment and we use https://registry.terraform.io/modules/Terraform-VMWare-Modules/vm/vsphere/latest now.
It fails because it needs a newer version of terraform:

```
$ terraform init
Initializing modules...
Downloading Terraform-VMWare-Modules/vm/vsphere 2.0.0 for vm...
- vm in /.terraform/modules/vm
Error: Unsupported Terraform Core version
  on /.terraform/modules/vm/versions.tf line 2, in terraform:
   2:   required_version = ">= 0.13.4"
```

Thank you very much :-)
Alexander

**Comment by LeePorte** [comment]
Hi Alexander,

We got round to this in https://github.com/alphagov/paas-docker-cloudfoundry-tools/pull/206. The tag you'll want for this version of the container is `46515235832a37ce826c1fd2b6c27f350977c80a`

Thanks

Lee
